### ISSUE TITLE
Support remaining API endpoints

### ISSUE THREAD

**Issue by UweTrottmann** [UweTrottmann/tmdb-java#4]
http://docs.themoviedb.apiary.io/

https://github.com/UweTrottmann/tmdb-java/blob/master/CHANGELOG.md#supported-api-calls

**Comment by migueljteixeira** [comment]
I pushed a pull request with updates to the Movie Service.
( https://github.com/UweTrottmann/tmdb-java/pull/21 )

What was added:
- alternative titles
- credits
- images
- keywords
- releases
- videos
- latest movie added
- lists
- reviews

I intend to update the other services in the following days.
Thanks ;)
Miguel

**Comment by urizev** [comment]
New endpoint for

`/person/{id}/tagged_images`

at pull request #30

**Comment by ProIcons** [comment]
Completed at #44
