### ISSUE TITLE
Remove myself from pom.xml if Sonatype OSSRH allows it

### ISSUE THREAD

**Issue by UweTrottmann** [UweTrottmann/tmdb-java#46]

**Comment by ProIcons** [comment]
Got a question though. What's the point of removing it?
The project is on Public Domain which means, everyone can do whatever they want with it, having a developer on the POM it's not a big deal. What makes you want to remove your self from the pom?

**Comment by UweTrottmann** [comment]
Sonatype OSSRH requires a developer tag...
