### ISSUE TITLE
MovieService may be broken

### ISSUE THREAD

**Issue by mrkaiser** [UweTrottmann/tmdb-java#59]
After reading the retrofit 2 documentation and looking through the source, at least any `@Get` is possibly broken. The current TMDB API returns all info on `movie/{movie_id}`. However it appears that in the source that there are many calls to `movie/{movie_id}/somecall` (e.g `movie/{movie_id}/release_dates`. All returns appear to be null. I could make a PR that just returns the entire result on summary, but then the semantics of the API kinda break down. I can't find anything in the retrofit documentation on how to parse and return only specific parts of the response body. I just have learned about retrofit so I could be missing something.

**Comment by ProIcons** [comment]
Have you read the TMDB's API Documentation?
Every aspect of the Service is being used. Run the tests, if they pass (which they will unless service is facing some internal errors) it means that you are doing something incorrectly. Also note on the new movies that are announced there are no many data. If you think i got this all wrong and misunderstood you please provide an example with working ids.

**Comment by mrkaiser** [comment]
Yeah I misread the API documentation (on both sides). Thanks. Sorry for the open issue.
