### ISSUE TITLE
Provide existing configured OkHttpClient

### ISSUE THREAD

**Issue by yschimke** [UweTrottmann/tmdb-java#78]
Also raising on https://github.com/UweTrottmann/trakt-java

See https://square.github.io/okhttp/4.x/okhttp/okhttp3/-ok-http-client/#okhttpclients-should-be-shared

Would you accept a PR?

**Comment by ProIcons** [comment]
Noone stops you from creating a Pull Request. If it's meaningful and correct it will be merged.

**Comment by UweTrottmann** [comment]
Just subclass `Tmdb` and override `okHttpClient()`.
