### ISSUE TITLE
Update Entity IDs to Long?!

### ISSUE THREAD

**Issue by ProIcons** [UweTrottmann/tmdb-java#80]
Should we update the ids of the entities from ints to longs?

**Comment by UweTrottmann** [comment]
Any particular reason why? Link?

**Comment by UweTrottmann** [comment]
If at all I would just change everything and release a major new version.

To get an estimation of when Integer.MAX_VALUE might be reached:
- What is the highest ID right now?
- How long has TMDB existed?

But in any case I doubt we'll ever reach that 2 billion in our life times.
