### ISSUE TITLE
include_adult missing for search.tv method

### ISSUE THREAD

**Issue by mlaggner** [UweTrottmann/tmdb-java#83]
the TMDB api offers a flag for including adult TV shows in the search service (https://developers.themoviedb.org/3/search/search-tv-shows), but this lib is missing that.

**Comment by UweTrottmann** [comment]
Thanks. Does this have an effect? Or probably was added later?

Anyhow, pull request welcome: just add a parameter to existing methods. No need to duplicate them.

**Comment by mlaggner** [comment]
I do not know whether this has been added afterwards or not. But not sending this flag suppresses TMDB sending adult results back to the caller

I will add this per PR - are you not afraid of the breaking change of the method signature?

**Comment by UweTrottmann** [comment]
It's not worth to avoid a simple breaking change like this vs. the additional maintenance burden (code duplication).

Merged, so closing.
