### ISSUE TITLE
Add trending endpoint

### ISSUE THREAD

**Issue by Sarlay** [UweTrottmann/tmdb-java#92]
Hello !

First of all thank you for this wrapper you did an amazing job,
I saw that tmdb offers a "trending" endpoint [(here)](https://developers.themoviedb.org/3/trending/get-trending)
I couldn't find the appropriate way to call that endpoint using this wrapper, is it already implemented ?

Thanks in advance !

**Comment by UweTrottmann** [comment]
https://github.com/UweTrottmann/tmdb-java/tree/main/src/main/java/com/uwetrottmann/tmdb2/services

Looks like this wasn't contributed, yet.

**Comment by UweTrottmann** [comment]
Added by #94!
